### ISSUE TITLE
Binary Permissions and Quarantine.

### ISSUE THREAD

**Issue by gregglind** [chriskol/Desktop-Google-Keep-OSX#14]
1.  Yes, build it from source, if you can.  
2.  To use the binary, this is one method to fix the permissions.

```bash
# assuming you moved the app bundle to /Applications
sudo xattr -r -d com.apple.quarantine /Applications/Desktop-Google-Keep-OSX.app
```

**Comment by chriskol** [comment]
Are people getting Gatekeeper issues with the binary now? I built my own (obviously haha) and was unaware there were issues with it.

**Comment by gregglind** [comment]
I did :). Other might not.

(Also, the tgz link on the "page" is busted.)

Super thank you for making this.   "Keep"ing in a tab was tedious!

**Comment by chriskol** [comment]
No problem.  Was a great way for me to dip my toes in coding and learn sometimes it's 6 hours of research and 5mins of code :P. I'll get around to updating the readmes of the possibility of the issue when I get a chance.  I've been getting annoying quarantine warnings for things since the Catalina update so I wouldn't be surprised.

**Comment by gregglind** [comment]
Yes, it's Catalina related for me too.

Some other authors include a little 'fixPermissions.sh' file.  I wish I
knew the right answer.

**Comment by gregglind** [comment]
Thank you for doing the 6 hours of research.  It is often the very very
hard part, where all the frustration is.

I am too old for research :).
