### ISSUE TITLE
Better icon

### ISSUE THREAD

**Issue by Palivec** [chriskol/Desktop-Google-Keep-OSX#5]
Hi, I find the current icon a bit blurry, with the shade around, too large compared to the others, not the nicest in the dock. How about using a neat one, the official google one ? Its also used in their chrome app.

PNG Link : https://ssl.gstatic.com/gb/images/a/17bdcddea9.png

**Comment by chriskol** [comment]
I think that might be because of the size of your doc?  I agree it's cleaner but this is the result of using that png related to what already exists as it appears in my doc.  It's way smaller than my other dock icons.

https://www.dropbox.com/s/bxz0437zzs4vvvk/Screenshot%202017-08-30%2019.51.56.png?dl=0

**Comment by Palivec** [comment]
I send a picture of my dock, I see it doesn't look the same as in your case. However, the old icon has an outdated style, maybe you can make a medium size.

PNG Link : http://www.imgup.cz/images/2017/08/31/dock-keep30415.png

**Comment by chriskol** [comment]
Wow.  Took a look at specs and Apple says an application/dock icon should be 1024px haha

**Comment by marcoamadeo** [comment]
When i open the app, it always open in this position
![schermata 2018-01-23 alle 21 25 58](https://user-images.githubusercontent.com/10888283/35306297-17e1a43a-0084-11e8-8d1f-a1d360d9e502.png)

**Comment by Palivec** [comment]
Hi, it work fine for me.
